# Generated by Django 6.0.1 on 2026-01-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('view_dashboard', 'Can view system dashboard'), ('assign_asset', 'Can assign assets'), ('dispose_asset', 'Can dispose assets')]},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'permissions': [('view_maintenance_costs', 'Can view maintenance costs')]},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'permissions': [('adjust_stock', 'Can adjust stock levels')]},
        ),
    ]
