# Generated by Django 6.0.1 on 2026-01-27 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_asset_options_alter_maintenancerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'permissions': [('view_dashboard', 'Can view system dashboard'), ('assign_asset', 'Can assign assets'), ('dispose_asset', 'Can dispose assets')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetassignment',
            options={'ordering': ['-assigned_on'], 'verbose_name': 'Asset Assignment', 'verbose_name_plural': 'Asset Assignments'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-performed_on'], 'permissions': [('view_maintenance_costs', 'Can view maintenance costs')], 'verbose_name': 'Maintenance Record', 'verbose_name_plural': 'Maintenance Records'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name'], 'permissions': [('adjust_stock', 'Can adjust stock levels')], 'verbose_name': 'Stock Item', 'verbose_name_plural': 'Stock Items'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
