# Generated by Django 6.0.1 on 2026-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_asset_options_alter_assetassignment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='model',
            new_name='model_name',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
