# Generated by Django 6.0.1 on 2026-04-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_auditlog_action_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assetassignment',
            options={'ordering': ['-assigned_on']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-performed_on']},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp']},
        ),
    ]
